version: '2'
services:
  course_management-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/course_management/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=course_management
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
